[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect API requests to the appropriate function
[[redirects]]
  from = "/api/listings"
  to = "/.netlify/functions/get-listings"
  status = 200

[[redirects]]
  from = "/api/listings/*"
  to = "/.netlify/functions/get-listings?id=:splat"
  status = 200

[[redirects]]
  from = "/api/inquiries"
  to = "/.netlify/functions/submit-inquiry"
  status = 200

# SPA redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 